### ISSUE TITLE
recent update to 1.8 causes Unity Get Project Version to bomb

### ISSUE THREAD

**Issue by erichfrazer** [Dinomite-Studios/unity-azure-pipelines-tasks#162]
we are using "classic style" (non YAML) Unity Get Project Version. When it runs, it fails and shows this error:

    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\agent\_work\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.30\unity-get-project-version.js:4:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

##[error]Exit code 1 returned from process: file name 'D:\agent\externals\node\bin\node.exe', arguments '"D:\agent\_work\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.30\unity-get-project-version.js"'.

anybody else see this?

**Comment by erichfrazer** [comment]
I'm seeing the unity build task failing, too. Need some direct support on this, this update has killed our builds. I've written you before, from my microsoft address, I hope you reply, Dino!
thanks.

**Comment by Ighh** [comment]
You are not alone I got issues with the Unity CMD task as well after their release.

As a quick solution to build our solution I used a powershell task, you just loose the direct compilation output.

```
  - task: PowerShell@2
         displayName: Build Client
         inputs:
         targetType: 'inline'
         script: |
           Start-Process -FilePath "Unity.exe" -WorkingDirectory "C:/Program Files/Unity/Hub/Editor/2020.2.1f1/Editor" -ArgumentList "-quit -batchmode -projectPath `"$(Build.SourcesDirectory)`" -buildTarget Win64 -executeMethod BuildSolution.BuildClient" -Wait -PassThru

**Comment by WikkidEdd** [comment]
I had the same issue, but Dino fixed it over the weekend. Works now 👍

**Comment by FejZa** [comment]
This was fixed in a recent release. Thanks everyone for reporting.
