### ISSUE TITLE
UnityActivateLicenseV1 hangs at end of Unity batch mode

### ISSUE THREAD

**Issue by joaocc** [Dinomite-Studios/unity-azure-pipelines-tasks#200]
Hi,
This seems to have been introduced in v2.8.6.

Previously, the licence activation would sometimes choose the wrong project (https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/181) but would complete as follows:

```
[Performance] ProcessService.OnProjectLoaded                              :        1 samples, Peak.  18.7 ms (1.0x), Avg.  18.7 ms, Total. 18.73 ms (0.0%)
Cleanup mono
Exiting batchmode successfully now!
Unwatch  C:\a\1\s\Logs\UnityActivationLog_2022-05-19-23-16-41.log
=============================== UNITY LOG END ================================
Unity editor license activated
Finishing: Activate Unity License
```

With the new version, the job takes forever to complete, and ends up being killed by exceeding timeout (1h)
```
##[debug]   -serial
##[debug]   ***
##[debug]   -projectPath
##[debug]   C:\a\1\s\PROJROOTNAME\
##[debug]   -logfile
##[debug]   C:\a\1\s\Logs\UnityActivationLog_2022-06-17-19-15-38.log
"C:\Program Files\Unity\Hub\Editor\2019.4.28f1\Editor\Unity.exe" -batchmode -quit -nographics -username *** -password *** -serial *** -projectPath C:\a\1\s\PROJROOTNAME\ -logfile C:\a\1\s\Logs\UnityActivationLog_2022-06-17-19-15-38.log
================================ UNITY LOG ===================================
Tail starting...

(...)

[Performance] ProcessService.OnProjectLoaded                              :        1 samples, Peak.  22.3 ms (1.0x), Avg.  22.3 ms, Total. 22.31 ms (0.1%)

##[debug]Exit code 0 received from tool 'C:\Program Files\Unity\Hub\Editor\2019.4.28f1\Editor\Unity.exe'
##[debug]STDIO streams have closed for tool 'C:\Program Files\Unity\Hub\Editor\2019.4.28f1\Editor\Unity.exe'
Cleanup mono
Exiting batchmode successfully now!
##[debug]Re-evaluate condition on job cancellation for step: 'Activate Unity License'.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Activate Unity License
```

Since "-quit" is already specified, not sure what may be the cause.
Thanks

**Comment by GunLengend** [comment]
Having the same issue here

**Comment by GunLengend** [comment]
I got same issue, specific the version like UnityActivateLicenseTask@1.0.42 will solve the problem

**Comment by joaocc** [comment]
@GunLengend, while being a suitable workaround for people who don't need (https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/181), reverting to 1.0.42 will not address those that needed the fix which was introduced in 1.0.43.

**Comment by GunLengend** [comment]
@joaocc  thank your for your time, and yes, it's just a work around for someone really need to build for the release deadline ( like me :D )

**Comment by davidisaza** [comment]
I am having the same issue, and since I am running Azure Devops Server it does not allow me to specify the version number like @GunLengend said, this seems to be available on Azure Devops Service.

**Comment by FejZa** [comment]
Fixed in v2.9.0 of the extension package.
